### ISSUE TITLE
Moonbeam demo cannot work with required Turing version

### ISSUE THREAD

**Issue by morkeltry** [OAK-Foundation/xcm-demo#113]
[Moonbeam demo](https://github.com/OAK-Foundation/xcm-demo/tree/master#moonbeam-evm-smart-contract-automation) pre-requisite is given as
> Turing Network 	[v2.0.0](https://github.com/OAK-Foundation/OAK-blockchain/releases/tag/v2.0.0)

however, [`sendExtrinsicPromise` in `common.js`](https://github.com/OAK-Foundation/xcm-demo/blob/de25c6fa34a5f81129ebdbcac26d8d3531336202/src/moonbeam/common.js#L113-L122)  contains no `scheduleAs` parameter.

Result:
```
b). Send extrinsic from moonbase-local to turing-local to schedule task. Listen to TaskScheduled event on turing-local chain ...
Listen XCMP task events
Error: The scheduleAs parameter should not be empty
    at Object.scheduleXcmpTimeTaskWithPayThroughRemoteDerivativeAccountFlow (..../node_modules/@oak-network/src/index.ts:244:15)
    at scheduleTask (..../src/moonbeam/common.js:200:11)
    at main (..../src/moonbeam/moonbase-local.js:45:3)
```

`scheduleAs` parameter is apparently [no longer required in v.2.1.4](https://github.com/OAK-Foundation/OAK-blockchain/pull/499) but I could not verify whether the demo works with that version due to

**Related issue**
[Apparently wrong version downloads from releases v.2.14](https://github.com/OAK-Foundation/OAK-blockchain/issues/518)

**Comment by chrisli30** [comment]
Let’s make sure the instructions of Moonbeam demo in README.md is up-to-date too.

**Comment by chrisli30** [comment]
Hi @morkeltry,

We have re-tested the xcm-demo and made some changes in #114. Please take a look at the new instructions, give it another try, and let us know how it goes!

The xcm-demo code was updated to use [OAK-blockchain v2.1.4](https://github.com/OAK-Foundation/OAK-blockchain/releases/tag/v2.1.4), but instructions in README.md weren’t. This PR is to update the README.md to make sure release versions match the code.

Thank you for your feedback 👍
